const data = [
  {
    children: ["Fish", "Meat"],
    _id: "61b0d3975741dd2e949d540a",
    parent: "Fish & Meat",
    type: "Grocery",
    icon: "https://i.ibb.co/y0zXYj5/carp-fish.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Dry Fruits", "Fresh Fruits", "Fresh Vegetable"],
    _id: "61b0d3975741dd2e949d5409",
    parent: "Fruits & Vegetable",
    type: "Grocery",
    icon: "https://i.postimg.cc/RZ275n3f/cabbage.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Fresh Seafood"],
    _id: "61b0d3975741dd2e949d5408",
    parent: "Fresh Seafood",
    type: "Grocery",
    icon: "https://i.ibb.co/pfscwF4/shrimp.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Oil", "Rice", "Flour", "Dry Vegetable", "Spices & Mixes"],
    _id: "61b0d3975741dd2e949d5407",
    parent: "Cooking Essentials",
    type: "Grocery",
    icon: "https://i.ibb.co/hBv30Rt/frying-pan.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Bread", "Cereal"],
    _id: "61b0d3975741dd2e949d5406",
    parent: "Breakfast",
    type: "Grocery",
    icon: "https://i.ibb.co/dgPzSt7/bagel.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Tea", "Water", "Juice", "Coffee", "Energy Drinks"],
    _id: "61b0d3975741dd2e949d5405",
    parent: "Drinks",
    type: "Grocery",
    icon: "https://i.ibb.co/Dz8LKDX/soft-drink.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Dairy", "Ice Cream", "Butter & Ghee"],
    _id: "61b0d3975741dd2e949d5404",
    parent: "Milk & Dairy",
    type: "Grocery",
    icon: "https://i.ibb.co/181Qpm8/milk.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Organic Food"],
    _id: "61b0d3975741dd2e949d5403",
    parent: "Organic Food",
    type: "Grocery",
    icon: "https://i.ibb.co/xmGhNRF/apple.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Honey"],
    _id: "61b0d3975741dd2e949d5402",
    parent: "Honey",
    type: "Grocery",
    icon: "https://i.postimg.cc/65JSfy6H/honey-1.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Sauces", "Pickles & Condiments"],
    _id: "61b0d3975741dd2e949d5401",
    parent: "Sauces & Pickles",
    type: "Grocery",
    icon: "https://i.postimg.cc/mk09xvk4/chili-sauce.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Jam & Jelly"],
    _id: "61b0d3975741dd2e949d5400",
    parent: "Jam & Jelly",
    type: "Grocery",
    icon: "https://i.postimg.cc/rmLvfsMC/strawberry-jam-1.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Chocolate", "Chips & Nuts", "Canned Food"],
    _id: "61b0d3975741dd2e949d53ff",
    parent: "Snacks & Instant",
    type: "Grocery",
    icon: "https://i.ibb.co/HT7c6VT/chips.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Cakes", "Biscuits"],
    _id: "61b0d3975741dd2e949d53fe",
    parent: "Biscuits & Cakes",
    type: "Grocery",
    icon: "https://i.postimg.cc/0jVF5Cmc/cookie.png",
    status: "Show",
    __v: 0,
  },
  {
    children: [
      "Cleaner",
      "Laundry",
      "Air Freshener",
      "Water Filter",
      "Pest Control",
      "Cleaning Tools",
    ],
    _id: "61b0d3975741dd2e949d53fd",
    parent: "Household Tools",
    type: "Home Accessories",
    icon: "https://i.ibb.co/rdY6zL0/cleaner.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Baby Food", "Baby Accessories"],
    _id: "61b0d3975741dd2e949d53fc",
    parent: "Baby Care",
    type: "Health Care",
    icon: "https://i.postimg.cc/QNqrnQBB/baby.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Cat Care", "Dog Care", "Bird Care"],
    _id: "61b0d3975741dd2e949d53fb",
    parent: "Pet Care",
    type: "Grocery",
    icon: "https://i.postimg.cc/RVVzrWfg/cat.png",
    status: "Show",
    __v: 0,
  },
  {
    children: [
      "Bath",
      "Cosmetics",
      "Oral Care",
      "Skin Care",
      "Body Care",
      "Shaving Needs",
    ],
    _id: "61b0d3975741dd2e949d53fa",
    parent: "Beauty & Health",
    type: "Health Care",
    icon: "https://i.postimg.cc/gjz1P7wx/beauty.png",
    status: "Show",
    __v: 0,
  },
  {
    children: ["Sports", "Fitness"],
    _id: "61b0d3975741dd2e949d53f9",
    parent: "Sports & Fitness",
    type: "Sports & Fitness",
    icon: "https://i.ibb.co/qNCvxT0/dumbbell.png",
    status: "Show",
    __v: 0,
  },
];

export default data;
